### ISSUE TITLE
Poduct L-Serine is not in the metanetx_universal_model_bigg database  ???

### ISSUE THREAD

**Issue by marangiop** [biosustain/cameo#202]
Hello everybody, I just installed cameo on a virtual environment in Linux (which is being run through a Virtual Machine) and when I run the following code,  I get an error:

from cameo.api import design
design(product='L-Serine')

Starting searching for compound L-Serine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paolo/Cameo_virtuenv/cameo/local/lib/python2.7/site-packages/cameo/api/designer.py", line 185, in __call__
    raise KeyError("Product %s is not in the %s database" % (product, database.id))
KeyError: u'Product L-Serine is not in the metanetx_universal_model_bigg database'

Has anybody got the same error? Can anybody help me out?

**Comment by phantomas1234** [comment]
Works for me and also on http://try.cameo.bio. Can you try upgrading to the latest version using `pip install cameo - -
upgrade` and check if the problem persists?If it does, please provide us with some information on your system, python installation etc.

**Comment by marangiop** [comment]
I checked and I have the latest version of cameo.  
I have a Windows 10 OS, but I am running cameo on Ubuntu through a virtual machine  I have also installed the cameo package with "pip install cameo" after setting up a virtual environment.  Is this enough information?

**Comment by marangiop** [comment]
When I run the code that you just sent me I got the same outputs as you.

I also get an output when I directly use the metenetx ID

**Comment by marangiop** [comment]
I attempted to run 

from cameo.api import design
design(product='L-Serine')

and I got the same error again

**Comment by phantomas1234** [comment]
Ok this is super weird :-) can you try `design('serine')`? Are you copy pasting the L-serine from somewhere so that it maybe contains some weird utf-8 character for the dash maybe? Not sure how to approach this since it seems to be working fine for me and also in Linux docker containers we use all the time.  Could you maybe share the virtual image with me maybe? I am sorry that you have this bad experience with cameo.

**Comment by marangiop** [comment]
I tried the code you sent, still got an error, will send you the screenshot tomorrow if you like

I just shared my virtual image (15GB) with a Filemail link that I sent to your e-mail address. 

I really hope that we can find a solution to this

**Comment by phantomas1234** [comment]
Hi,w thanks for sending me the image. I am sorry, I can't really work on this right now, but I'll see that next sprint (starting next week) someone else will take care of this. Thanks for your patience.

**Comment by sgalkina** [comment]
@marangiop we just released the new version with the fix. Please upgrade cameo to the latest version `pip install --upgrade cameo` and try to run the code again. Thank you for sending the virtual image, it was very helpful.

**Comment by phantomas1234** [comment]
We closed this @marangiop, but please let us know if you're problem still persists.
