### ISSUE TITLE
Issues loading a local model

### ISSUE THREAD

**Issue by navborg** [biosustain/cameo#203]
Hi, 

I am just installed cameo on a virtual machine and tried to load the 'iJO1366.jason' model and get the following error. Does anyone know what this may be occuring?

Thanks, 

Naveed 

>>> from cameo import models
>>> model = load_model('iJO1366.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/modninja/Documents/Cameo_Repo/cameo/cameo/io.py", line 55, in load_model
    model = load_webmodel(path_or_handle, solver_interface)
  File "/home/modninja/Documents/Cameo_Repo/cameo/cameo/models/webmodels.py", line 58, in load_webmodel
    raise e
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='darwin.di.uminho.pt', port=80): Max retries exceeded with url: /models/models.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad4e57f950>, 'Connection to darwin.di.uminho.pt timed out. (connect timeout=3)'))
>>>

**Comment by Midnighter** [comment]
Hi @navborg, thank you for reporting this. There are two things to check:

1. If you are trying to load a remote model, you should write the name without format, i.e., `load_model('iJO1366')`.
2. Are you sure that you have a working internet connection from within your virtual machine? Please test this with a browser or other program.

**Comment by phantomas1234** [comment]
The server at minho has a blacklist maybe you're on it. The whole of DTU is on it. Are you sure your model is in the current working directory?
