### ISSUE TITLE
AttributeError: 'Solution' object has no attribute 'f'

### ISSUE THREAD

**Issue by Ravasz** [biosustain/cameo#219]
Hi there,

I was trying to execute the following code under Cameo 0.11.6, Python 3.7: 
```
from cameo import load_model, fba
model = load_model('models/CD4T1670.xml')
new_solution = model.optimize()
fba_result = fba(model)
print(fba_result)
```

Got the following error message:

```
Traceback (most recent call last):
  File "/home/mate/code/met_model/src/cd4.py", line 5, in <module>
    fba_result = fba(model)

  File "/home/mate/code/venv/cameo-p3/lib/python3.7/site-packages/cameo/flux_analysis/simulation.py", line 79, in fba
    result = FluxDistributionResult.from_solution(solution)

  File "/home/mate/code/venv/cameo-p3/lib/python3.7/site-packages/cameo/flux_analysis/simulation.py", line 395, in from_solution
    return cls(solution.fluxes, solution.f, *args, **kwargs) 
AttributeError: 'Solution' object has no attribute 'f'
```
In line 395, replacing "solution.f" with "solution.objective_value" seems to solve the issue

**Comment by Midnighter** [comment]
Yes, please take a look at #218. It will be fixed soon :smiley:

**Comment by Ravasz** [comment]
Oops, I did not see that. Thanks for the quick reply!
